import {
  LucideAudioLines,
  LucideChevronDown,
  LucideChevronUp,
  LucideCopy,
  LucideEllipsisVertical,
  LucideGrid2x2,
  LucideGrid3x3,
  LucideGripVertical,
  LucideImageUp,
  LucideLayers,
  LucideListFilter,
  LucideListMusic,
  LucideListStart,
  LucideLoaderCircle,
  LucideMinus,
  LucideMusic2,
  LucidePause,
  LucidePencil,
  LucidePlay,
  LucideRepeat2,
  LucideSave,
  LucideSearch,
  LucideShuffle,
  LucideSkipBack,
  LucideSkipForward,
  LucideSquare,
  LucideSquarePlus,
  LucideTrash2,
  LucideVolume1,
  LucideVolume2,
  LucideVolumeX,
  LucideX,
} from '@lucide/angular';

export const iconSet = {
  PlayIcon: LucidePlay.icon,
  PauseIcon: LucidePause.icon,
  PrevIcon: LucideSkipBack.icon,
  NextIcon: LucideSkipForward.icon,
  PlayNextIcon: LucideListStart.icon,
  PlaylistIcon: LucideListMusic.icon,
  RepeatIcon: LucideRepeat2.icon,
  GridBigIcon: LucideGrid2x2.icon,
  GridSmallIcon: LucideGrid3x3.icon,
  TracksIcon: LucideMusic2.icon,
  LoadingIcon: LucideLoaderCircle.icon,
  PlaylistIco: LucideListMusic.icon,
  AudioWaveIcon: LucideAudioLines.icon,
  SessionIcon: LucideLayers.icon,
};

export const actionsIconSet = {
  SearchIcon: LucideSearch.icon,
  DeleteIcon: LucideTrash2.icon,
  AddIcon: LucideSquarePlus.icon,
  ActionsMenu: LucideEllipsisVertical.icon,
  EditIcon: LucidePencil.icon,
  CrossIcon: LucideX.icon,
  SaveIcon: LucideSave.icon,
  FilterIcon: LucideListFilter.icon,
  CollapsedArrowIcon: LucideChevronDown.icon,
  ExpandedArrowIcon: LucideChevronUp.icon,
  ShuffleIcon: LucideShuffle.icon,
  UploadImageIcon: LucideImageUp.icon,
  CloseAppIcon: LucideX.icon,
  MinimizeIcon: LucideMinus.icon,
  MaximizeIcon: LucideSquare.icon,
  UnmaximizeIcon: LucideCopy.icon,
  DragIcon: LucideGripVertical.icon,
};

export const volumeIconSet = {
  MutedIcon: LucideVolumeX.icon,
  LowIcon: LucideVolume1.icon,
  NormalIcon: LucideVolume2.icon,
};

