import {
  AudioLinesIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  CopyIcon,
  EllipsisVerticalIcon,
  Grid2x2Icon,
  Grid3x3Icon,
  ImageUpIcon,
  ListFilterIcon,
  ListMusicIcon,
  ListStartIcon,
  LoaderCircleIcon,
  MinusIcon,
  Music2Icon,
  PauseIcon,
  PencilIcon,
  PlayIcon,
  Repeat2Icon,
  SaveIcon,
  SearchIcon,
  ShuffleIcon,
  SkipBackIcon,
  SkipForwardIcon,
  SquareIcon,
  SquarePlusIcon,
  Trash2Icon,
  Volume1Icon,
  Volume2Icon,
  VolumeXIcon,
  XIcon,
} from 'lucide-angular';

export const iconSet = {
  PlayIcon: PlayIcon,
  PauseIcon: PauseIcon,
  PrevIcon: SkipBackIcon,
  NextIcon: SkipForwardIcon,
  PlayNextIcon: ListStartIcon,
  PlaylistIcon: ListMusicIcon,
  RepeatIcon: Repeat2Icon,
  GridBigIcon: Grid2x2Icon,
  GridSmallIcon: Grid3x3Icon,
  TracksIcon: Music2Icon,
  LoadingIcon: LoaderCircleIcon,
  PlaylistIco: ListMusicIcon,
  AudioWaveIcon: AudioLinesIcon,
};

export const actionsIconSet = {
  SearchIcon: SearchIcon,
  DeleteIcon: Trash2Icon,
  AddIcon: SquarePlusIcon,
  ActionsMenu: EllipsisVerticalIcon,
  EditIcon: PencilIcon,
  CrossIcon: XIcon,
  SaveIcon: SaveIcon,
  FilterIcon: ListFilterIcon,
  CollapsedArrowIcon: ChevronDownIcon,
  ExpandedArrowIcon: ChevronUpIcon,
  ShuffleIcon: ShuffleIcon,
  UploadImageIcon: ImageUpIcon,
  CloseAppIcon: XIcon,
  MinimizeIcon: MinusIcon,
  MaximizeIcon: SquareIcon,
  UnmaximizeIcon: CopyIcon,
};

export const volumeIconSet = {
  MutedIcon: VolumeXIcon,
  LowIcon: Volume1Icon,
  NormalIcon: Volume2Icon,
};
